# Generated by Django 4.2 on 2023-04-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
