# Generated by Django 4.2 on 2023-04-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_audio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='duration',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
